site_name: awesome-gee-community-datasets
site_description: Community Datasets in Google Earth Engine
site_author: Samapriya Roy
site_url: https://github.com/samapriya

# Repository
repo_name: awesome-gee-community-datasets
repo_url: https://github.com/samapriya/awesome-gee-community-datasets

# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Samapriya Roy'


# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Google Sans
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: logo

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samapriya
    - icon: fontawesome/brands/medium
      link: https://medium.com/@samapriyaroy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/samapriyaroy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samapriya

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



# Page tree
nav:
  - Introduction: index.md
  - Catalog Stats: stats.md
  - Population & Socioeconomic:
    - High Resolution Settlement Layers: projects/hrsl.md
    - GPW Version 4 Admin Units: projects/GPWv4.md
    - geoBoundaries Global Database of Political Administrative Boundaries: projects/geoboundary.md
    - West Africa Coastal Vulnerability Mapping: projects/wacvm.md
    - Relative Wealth Index (RWI): projects/rwi.md
    - Social Connectedness Index (SCI): projects/sci.md
    - Gridded Global GDP and HDI (1990-2015): projects/gridded_gdp_hdi.md
    - Harmonized Global Critical infrastructure & Index (CISI): projects/cisi.md
    - Native Land (Indigenous Land Maps): projects/native.md
    - Gridded Sex-Disaggregated School-Age Population (2020): projects/wpschool.md
  - Geophysical, Biological & Biogeochemical:
    - Geomorpho90m Geomorphometric Layers: projects/geomorpho90.md
    - Bare Earth’s Surface Spectra 1980-2019: projects/bss.md
    - Normalized Sentinel-1 Global Backscatter Model Land Surface: projects/s1gbm.md
    - Soil Organic Carbon Stocks & Trends South Africa: projects/soc.md
    - Soil nematode abundance & functional group composition: projects/soil_nematode.md
    - Global maps of habitat types: projects/habitat.md
    - Soil carbon storage in terrestrial ecosystems of Canada: projects/scs.md
    - Irrecoverable carbon in Earth’s ecosystems: projects/irc.md
    - Global MODIS-based snow cover monthly values (2000-2020): projects/snow_cover.md
    - Global Surface water and groundwater salinity measurements (1980-2019): projects/salinity.md
  - Elevation and Bathymetry:
    - Copernicus Digital Elevation Model (GLO-30 DEM): projects/glo30.md
    - FABDEM (Forest And Buildings removed Copernicus 30m DEM): projects/fabdem.md
    - ASTER Global Digital Elevation Model (GDEM) v3: projects/aster.md
    - ASTER Global Water Bodies Database (ASTWBD) Version 1: projects/astwbd.md
    - General Bathymetric Chart of the Oceans (GEBCO): projects/gebco.md
    - Coastal National Elevation Database (CoNED) Project -Topobathymetric digital elevation models (TBDEMs): projects/tbdem.md
    - NOAA Sea-Level Rise Digital Elevation Models (DEMs): projects/slrdem.md
    - ÍslandsDEM v1.0 10m: projects/iceland_dem.md
  - Soil Properties:
    - Soil Grids 250m v2.0: projects/isric.md
    - Soil Properties 800m: projects/soilprop.md
    - iSDAsoil Predicted Soil Properties for Africa 30m: projects/isda.md
    - Polaris 30m Probabilistic Soil Properties US: projects/polaris.md
    - HiHydroSoil v2.0 layers: projects/hihydro_soil.md
    - Global Soil Salinity Maps (1986-2016): projects/global_salinity.md
  - Global Land Use and Land Cover:
    - Global Mangrove Project: projects/mangrove.md
    - Global Mangrove Distribution, Aboveground Biomass, and Canopy Height: projects/gmd.md
    - ESRI 2020 Global Land Use Land Cover from Sentinel-2: projects/esrilc2020.md
    - ESA WorldCover 10 m 2020 V100 InputQuality: projects/esa_iq.md
    - Global Impervious Surface Area (1972-2019): projects/gisa.md
    - Global urban extents from 1870 to 2100: projects/gue.md
    - World Settlement Footprint & Evolution: projects/wsf.md
  - Regional Land Use and Land Cover:
    - Mapbiomas Annual land cover and use maps: projects/mapbiomas.md
    - Land Change Monitoring, Assessment, and Projection (LCMAP) v1.2: projects/lcmap.md
    - West Africa Land Use Land Cover: projects/wa_lulc.md
    - South African National Land Cover 2018: projects/sa_nlc2018.md
    - Mississippi River Basin Floodplain Land Use Change (1941-2000): projects/floodplain_lc.md
    - Continental-scale land cover mapping at 10 m resolution over Europe: projects/elc.md
    - Digital Earth Australia(DEA) Landsat Land Cover 25m v1.0.0: projects/dea_lc.md
    - High-resolution annual forest land cover maps for Canada's forested ecosystems (1984-2019): projects/ca_lc.md
    - Oil Palm Plantation Layers: projects/oil-palm.md
    - Rasterized building footprint dataset for the US: projects/usbuild_raster.md
  - Hydrology:
    - OSM Water Layer Surface Waters in OpenStreetMap: projects/osm_water.md
    - Global 30m Height Above the Nearest Drainage: projects/hand.md
    - HydroLAKES v1.0: projects/hydrolakes.md
    - Global River Width from Landsat (GRWL): projects/grwl.md
    - Global coastal rivers and environmental variables: projects/rivermouth.md
    - Global River Deltas and vulnerability: projects/river_deltas.md
    - Global georeferenced Database of Dams(GOODD): projects/goodd.md
    - Global Hydrologic Curve Number(GCN250): projects/gcn250.md
    - Global high-resolution floodplains (GFPLAIN250m): projects/gfplain250.md
    - Global river networks & Corresponding Water resources zones: projects/grn_wrz.md
    - National Wetland Inventory (Surface Water and Wetlands): projects/nwi.md
    - National Hydrography Dataset (NHD): projects/nhd.md
    - Tensor Flow Hydra Flood Models: projects/hydra_water.md
    - High-resolution gridded precipitation dataset for Peruvian and Ecuadorian watersheds (1981-2015): projects/gridded_ppt.md
  - Oceans and Shorelines:
    - Global Shoreline Dataset: projects/shoreline.md
    - Argo Float Data(Subset): projects/argo.md
    - Global gridded sea surface temperature (SSTG): projects/sstg.md
    - Global Storm Surge Reconstruction (GSSR) database: projects/gssr.md
    - Aqualink ocean surface and subsurface temperature subset: projects/aqualink.md
    - Plastic Inputs from Rivers into Oceans: projects/plastic.md
  - Agriculture, Vegetation and Forestry:
    - Landfire Mosaics LF v2.0.0: projects/landfire.md
    - Vegetation dryness for western USA: projects/veg_dry.md
    - ETH Global Sentinel-2 10m Canopy Height (2020): projects/canopy.md
    - Global Forest Carbon Fluxes (2001-2021): projects/cflux.md
    - Rangeland Analysis Platform layers: projects/rap.md
    - NASA Harvest Layers: projects/harvest.md
    - Benchmark maps Secondary Forest Brazil: projects/secondary_forest.md
    - Global irrigation areas (2001 to 2015): projects/global_irrigation.md
    - Tile Drained Croplands (30m): projects/tile.md
    - Global crop production tillage practices: projects/tillage.md
  - Global Utilities, Assets and Amenities Layers:
    - Global Power: projects/global_power.md
    - Facebook Electrical Distribution Grid Maps: projects/electric_grid.md
    - Harmonized Global Night Time Lights (1992-2020): projects/hntl.md
    - Global Roads Inventory Project: projects/grip.md
    - Global Mining Areas and Validation Datasets: projects/global_mining.md
    - Global Healthsites Mapping Project: projects/health_sites.md
    - Global fixed broadband and mobile (cellular) network performance: projects/speedtest.md
    - Global Power Plant Database: projects/pwplants.md
    - Global offshore wind turbine dataset: projects/gowt.md
    - Harmonised global datasets of wind and solar farm locations and power: projects/energy_farms.md
    - Global Database of Cement Production Assets: projects/gcd.md
    - Global Database of Iron and Steel Production Assets: projects/gid.md
    - Global Photovoltaics Inventory (2016-2018): projects/global_pv.md
  - EarthEnv Biodiversity ecosystems & climate Layers:
    - Global Consensus Landcover: projects/gcl.md
    - Global Freshwater Variables: projects/gfv.md
    - Global Habitat Heterogeneity: projects/ghh.md
    - Global 1-km Cloud Cover: projects/gcc.md
  - Weather and Climate Layers:
    - Global Reference Evapotranspiration Layers: projects/et0.md
    - Global Aridity Index: projects/ai0.md
    - Global Wind Atlas Datasets: projects/gwa.md
    - Global Solar Atlas Datasets: projects/gsa.md
    - International Satellite Cloud Climatology Project HXG Cloud Cover: projects/isccp_hxg.md
    - Current and projected climate data for North America (CMIP6 scenarios): projects/aogcm_cmip6.md
    - Terraclimate Individual years for +2C and +4C climate futures: projects/terraclim.md
    - MODIS Gap filled Long-term Land Surface Temperature Daily (2003-2020): projects/daily_lst.md
    - United States Drought Monitor Layers: projects/usdm.md
    - High-spatial-resolution Thermal-stress Indices over South and East Asia (HiTiSAE): projects/hitisae.md
    - Long-term Gap-free High-resolution Air Pollutants (LGHAP): projects/lghap.md
  - Global Events Layers:
    - Global Fire Atlas (2003-2016): projects/gfa.md
    - Archival NRT FIRMS Global VIIRS and MODIS vector data: projects/firms_vector.md
    - Monitoring Trends in Burn Severity (MTBS) 1984-2019: projects/mtbs.md
    - Landsat Burned Area: projects/lba.md
    - Global large flood events (1985-2016) : projects/flood.md
    - Global Landslide Catalog (1970-2019): projects/landslide.md
    - Geocoded Disasters (GDIS) Dataset (1960 – 2018): projects/gdis.md
  - License: license.md
  - Changelog: changelog.md
